### PR TITLE
Add basic HTML linter with support for writing tests

### LINKED ISSUE #49: Add linters for a consistent codebase
We talked about this briefly in Slack - the mix of using double and single quotes in our Jade templates right now is pretty awful. We don't have to limit ourselves to just Jade linting, though:
- Jade: https://github.com/emartech/gulp-jade-lint
- JS: http://eslint.org/
- SCSS: https://github.com/brigade/scss-lint

### PR DESCRIPTION
**Pull request by thomastuts**
Fixes #49 (at least the Jade part, not sure if there's any interest in CSS/JS linting). See https://github.com/mono-company/bedrock/wiki/Linting for an explanation on how linting works, and how to create tests.

### CODE REVIEW

**Comment by Wolfr** [comment]
This seems to work well. First I wrote a test similar to the existing one to check for href attributes on `a` elements:

````
module.exports = function ($) {
  const errors = [];
  let allAhasHref = true;

  $('a').each(function (index, el) {
    const $el = $(el);

    if (!$el.attr('href')) {
      allAhasHref = false;
    }
  });

  if (!allAhasHref) {
    errors.push('All anchors need a `href` attribute.');
  }

  return errors;
};
````

Now I am figuring out the code for when you use a BEM modifier class without actually naming the BEM element (this signifies wrong usage of BEM). The middle "if" statement could use some work. Will try to figure this out on my own but if you have time feel free to work on it.

````
module.exports = function ($) {
  const errors = [];
  let bemModifierWithoutBlock = true;

  $('*[class*="--"]').each(function (index, el) {
    const $el = $(el);

    if () { // needs work
      bemModifierWithoutBlock = false;
    }
  });

  if (!bemModifierWithoutBlock) {
    errors.push('If you use a modifier class you also need to use the block class. You cannot use the modifier separately in BEM.');
  }

  return errors;
};
````

**Comment by Wolfr** [comment]
Maybe one comment is that `gulp lint` is too generic as you are only linting the jade.

Maybe we should use some other term so if we have more linters in the future we can separate the commands: `gulp lintcss` `gulp lintjs` `gulp linthtml`.

I.e. if you are not delivering production JS it might make sense to only do linting on HTML and CSS.

(I don't have a specific need to implement CSS or JS linting for now)

**Comment by Wolfr** [comment]
@thomastuts just checking on this, the only todo is to change the `gulp lint` command to `gulp linthtml`.

**Comment by thomastuts** [comment]
@Wolfr Updated!

**Comment by thomastuts** [comment]
@Wolfr The following test checks for any elements that have a BEM modifier class, but not the BEM block class:

```js
module.exports = function ($) {
  const errors = [];
  let modifiersWithoutBlocks = [];

  $('*[class*="--"]').each(function (index, el) {
    const $el = $(el);
    const classes = $el.attr('class').split(' ');

    modifiersWithoutBlocks = [
      ...modifiersWithoutBlocks,
      ...classes.filter((cssClass) => !classes.includes(cssClass.split('--')[0]))
    ];
  });

  if (modifiersWithoutBlocks.length > 0) {
    errors.push(`
      If you use a modifier class you also need to use the block class. You cannot use the modifier separately in BEM.
      \n
      Offending classes: ${modifiersWithoutBlocks.map(cssClass => `.${cssClass}`).join(',')}
    `);
  }

  return errors;
};
```

Given the following input:

```jade
button.btn.btn--small.a-block--some-modifier(type="button") I am testing BEM!
```

 It will produce the following output:

image

**Comment by Wolfr** [comment]
Super :)

**Comment by Wolfr** [comment]
I wanted to apply this linting to a project and encountered an error - the icon mixin does not seem "available" to the linter. Have to investigate this.

> [13:56:53] 'linthtml' errored after 942 ms
> [13:56:53] TypeError: content/templates/_components/b-button-skins/06-btn-outline.jade:3
>     1| button.btn.btn-outline Outline button
>     2| button.btn.btn-outline
>   > 3|     +icon('add')
>     4|     span.btn-label Outline button with icon
>     5| 
>     6| br
>

**Comment by Wolfr** [comment]
I was able to reproduce this error in Bedrock core. I'll log an issue.

**Comment by Wolfr** [comment]
Fyi was this was closed because I was pruning/deleting some old branches, at some ppint it would be cool to have a linter again

**Pull request closed without merging**
