### PR TITLE
JSON configuration for project colors

### PR DESCRIPTION
**Pull request by tdurand**
I had a quick shot at #188 

- changed _settings.colors.scss to colors.json
- you still defined the path in bedrock.config
- works out the plumbing to have both styleguide color page working and inject those colors as scss variables to use during styling

My thoughs on this one, it kinds of reverse the current color configuration, I'm just afraid it could be a bit too magical where whose colors scss variable comes from... Needs to be well documented.

We could also defined a default colors.json location to avoid having to specify a path in the bedrock.config and simplify it.

Hopefully I understood correctly what you wanted to do, let me know

### CODE REVIEW

**Comment by Wolfr** [comment]
In general, I think the idea of having some project variables defined in JSON format for usage in both JS and CSS is very interesting.

Now, specifically about the `colors.json`, the way we are doing it here is not easy to understand.

Colleagues have commented in the past that they also don't like this idea that much.

Documenting it also won't help.

I think we need a different approach - here's my thinking.

My general goal is that Bedrock has “optionality” i.e. you can start from something simple.

In the current state the default SCSS file references both colors and has the icon font in comment.

I want the default SCSS file to be completely empty. Starting a new Bedrock needs to feel like starting a new Codepen.

What I mean is that it starts as a static site generator that does nothing except generate a website for you.

But the power of Bedrock is that can easily configure it to have a styleguide, colors etc.

One problem we have now is that we are basically parsing the color SCSS file with regexes to get the colors out. This is quite dirty.

What if somebody uses a different commenting style?

What if they use something like SCSS lint?

So, all of this JSON-related thinking was also related to having nicer output as in a nicer SCSS file, and to be able to fully control code that comes out of Bedrock.

The JSON should look like this:

```
{[
  {
     "name": "red",
     "hex": "#FF0000";
     "category": "functional";
  }
    {
     "name": "blue-a11y",
     "hex": "#FF0000";
     "category": "brand";
  }
```

Then the template loop for the docs can be something like this:

```
each color in colors
   -color.name
   .color-box(style="background:"+color.hex width="40" height="40")
````

This kind of data structure combined with a colors template in the styleguide will allow people to fully customize the output of their color documentation.

Sometimes you want to show categories, sometimes you want to keep it simple.

Sometimes each color has a description.

Sometimes there are different color sets.

Sometimes there are a gazillion colors (like in material design).

If we find a system with templating we can support all of those use cases.

And the SCSS will come from a template like this (no idea which template language we should use here)

````
// Use my CSS commenting style that I want

{loop through colors in colors.json}
${replacecode}: {replacecode}
{/loop}

````

This kind of template with placeholders that has some kind of loop through the JSON-defined colors will allow people to fully customize their final CSS.

What do you think?

**Comment by tdurand** [comment]
- I definitely agree with the default over configuration philosophy

- I agree that the JSON structure you are thinking about is way easier to work with for non-developers, and more flexible if we don't want the category, I was just doing a first shot at this as you didn't specify and wasn't really convince of my proposal anyway. 

- For the styleguide rendering templating I'm not sure I entirely follow, I guess you mean that we should update the mixin colorOverview() to take some variable like "showCategories" and maybe different rendering style ? Could you specify better this /  implement it yourself once I adapt the JSON structure ?

- Regarding the auto-generated SCSS variables from the JSON config, for now it's totally invisible from user point of view, it is injected by gulp before compiling the existing Sass files, and I'm simply generating the scss variables here:  https://github.com/usebedrock/bedrock/pull/206/files#diff-b13cec9c87759f15a282711fb16676c1R20 and injecting them here: https://github.com/usebedrock/bedrock/pull/206/files#diff-cb9a047e8dc8b60178794feb1699db21R27 . It's not writting to any scss files the user then can modify / add more things in it.

I think what I understand from your comment is you want the user to be aware that we inject the colors.json var in a certain way, ie have a colors.scss files that has some templating languages so the user can modify where we inject them / how we do it... Am I right ? This would mean that we should agree on the templating "anguage we use for this and I write some code to "pre-compile" this to the actual scss output to inject (basically what my getSassVariableToInject() is doing but by reading this on some file)  .

I must admit I'm really confused on what you think we should do for this, so any extra guidance would be helpful 😉

I must admit I am a bit confused on this, so any further explanation would help 😉

**Comment by tdurand** [comment]
Yes I think I get the idea / philosophy behind this but I'm not 100% convinced of the implementation. I think I see this templating feature as overkill because we are right now in the use case of colors, that no matter how I think about it in the end I see that the scss file we want to be generated will always be super simple like this:  _(maybe it could help if you can think about an use case where we would want something else as the generated scss color file)_

```scss
// generated _colors.scss file
$white: #fff 
$black: #000
... 
```

So I don't really see why we should provide this super "complex" templating feature for the `_colors.scss` file generation that would make bedrock more complex... _(unless we keep it invisble for the default usecase and document the fact you need to create your templating file if you want to customize the behaviour)_ . Maybe also it could help that you provide some usecase you would use this that is not colors related 😉 .

That said next week I can give a quick update to that PR with some of those ideas, I guess having something concrete to reflect on is easier for us to refine the idea etc..

To sum up, we would have:

1. a colors.json as specified that would be in the "content" folder
2. a _colors.template.scss ,that would be in the "content" folder a well alongside with the colors.json file. We could use mustache.js / handlebar syntax for a start ? 
3.  1 and 2 would be combine at compile time to generate the _colors.scss file that would be generated  where ? It would make sense for it to be in this "scss/settings" folder along with the icon font scss generated files. Also maybe rename this folder to "generated" with some file that explain not to touch this stuff directly.
4. The color-overview.pug will be adapted to the new JSON structure, but right now it is already doing what we want, it receives the JSON content in the some variable and then people do whatever they want in the pug file to display their color styleguide

let me know what you think 😉, and have a great week-end

**Comment by Wolfr** [comment]
Let’s wait a bit and let some of these ideas mature before we do anything too complicated. I think I have something interesting here but I think I should prove the use case with a better plan. Thanks for your intelligent feedback :-)

Verstuurd vanaf mijn iPhone

**Comment by tdurand** [comment]
Sounds good 👌

**Comment by Wolfr** [comment]
I am going to close this one for clarity so we know there is no specific merging that needs to happen for now.

**Pull request closed without merging**
